//////////////////////////////////////////////////////////////////////////////////////////////
//
// Verilog file generated by X-HDL - Revision 3.2.37  Dec. 3, 2003 
// Sat Nov 24 09:50:53 2007
//
//      Input file         : D:/Downloads/gaisler/grlib-gpl-1.0.16-b2314/mctrl2/amba.vhd
//      Design name        : amba
//      Author             : 
//      Company            : 
//
//      Description        : 
//
//
//////////////////////////////////////////////////////////////////////////////////////////////
//
   //----------------------------------------------------------------------------
   //  This file is a part of the GRLIB VHDL IP LIBRARY
   //  Copyright (C) 2003, Gaisler Research
   //
   //  This program is free software; you can redistribute it and/or modify
   //  it under the terms of the GNU General Public License as published by
   //  the Free Software Foundation; either version 2 of the License, or
   //  (at your option) any later version.
   //
   //  This program is distributed in the hope that it will be useful,
   //  but WITHOUT ANY WARRANTY; without even the implied warranty of
   //  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   //  GNU General Public License for more details.
   //
   //  You should have received a copy of the GNU General Public License
   //  along with this program; if not, write to the Free Software
   //  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
   //---------------------------------------------------------------------------
   // Package: 	amba
   // File:	amba.vhd
   // Author:	Jiri Gaisler, Gaisler Research
   // Description:	AMBA 2.0 bus signal definitions + support for plug&play
   //----------------------------------------------------------------------------
   parameter NAHBSLV = 1; 
   parameter NAPBSLV = 1; 
   parameter NAHBAMR = 4; 
   parameter[1:0] HTRANS_IDLE = 2'b00; 
   parameter[1:0] HTRANS_BUSY = 2'b01; 
   parameter[1:0] HTRANS_NONSEQ = 2'b10; 
   parameter[1:0] HTRANS_SEQ = 2'b11; 
   parameter[2:0] HBURST_SINGLE = 3'b000; 
   parameter[2:0] HBURST_INCR = 3'b001; 
   parameter[2:0] HBURST_WRAP4 = 3'b010; 
   parameter[2:0] HBURST_INCR4 = 3'b011; 
   parameter[2:0] HBURST_WRAP8 = 3'b100; 
   parameter[2:0] HBURST_INCR8 = 3'b101; 
   parameter[2:0] HBURST_WRAP16 = 3'b110; 
   parameter[2:0] HBURST_INCR16 = 3'b111; 
   parameter[2:0] HSIZE_BYTE = 3'b000; 
   parameter[2:0] HSIZE_HWORD = 3'b001; 
   parameter[2:0] HSIZE_WORD = 3'b010; 
   parameter[2:0] HSIZE_DWORD = 3'b011; 
   parameter[2:0] HSIZE_4WORD = 3'b100; 
   parameter[2:0] HSIZE_8WORD = 3'b101; 
   parameter[2:0] HSIZE_16WORD = 3'b110; 
   parameter[2:0] HSIZE_32WORD = 3'b111; 
   parameter[1:0] HRESP_OKAY = 2'b00; 
   parameter[1:0] HRESP_ERROR = 2'b01; 
   parameter[1:0] HRESP_RETRY = 2'b10; 
   parameter[1:0] HRESP_SPLIT = 2'b11; 
   parameter mctrl_rom = 0; 
   parameter mctrl_io = 1; 
   parameter mctrl_ram = 2;    